### ISSUE TITLE
TimestampBehavior return NULL

### ISSUE THREAD

**Issue by reverse-cat** [rmrevin/yii2-changelog#1]
created_at an updated_at fields in changelog mysql table dosen't filled automatically.

Короче, поля created_at и updated_at не заполняются. всегда значение NULL. 
Хотя сам TimestampBehavior работает на других моделях. Пытался править Behavior в файле changelog.php или дописать с нуля Behavior  в файле LogStorage но пока безрезультатно.

**Comment by rmrevin** [comment]
Fixed in 1.0.1 version, thanks for issue.
